name: Update KBO CSV

on:
  schedule:
    # 23:30 KST 실행 (UTC 14:30). 리뷰 반영 지연 고려 시 추가로 새벽 재실행을 하나 더 두어도 좋음.
    - cron: "30 14 * * *"
  workflow_dispatch: {}

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      RECHECK_DAYS: "7"           # 최근 7일 재검사(예정 포함 시 강제 재크롤)
      OUT: data/kbo_latest.csv

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          # 최소 의존성
          pip install selenium==4.23.1 beautifulsoup4 pandas

      - name: Run crawler (append-mode aware + pending refresh)
        run: |
          set -e
          python KBO_crawl.py

      - name: Commit CSV if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "data: refresh CSV (pending & recent ${RECHECK_DAYS}d recheck)"
          else
            echo "No file changes."
          fi

      - name: Push
        if: ${{ !cancelled() }}
        run: |
          # 로컬 브랜치가 origin보다 앞으로 갔을 때만 push
          AHEAD=$(git rev-list --left-right --count origin/$(git rev-parse --abbrev-ref HEAD)...HEAD | awk '{print $2}')
          if [[ "${AHEAD}" != "0" ]]; then
            git push
          else
            echo "Nothing to push."
          fi
