name: Update KBO CSV

on:
  workflow_dispatch:
    inputs:
      since:
        description: "시작일(YYYYMMDD), 비우면 DEFAULT_SINCE"
        required: false
        default: ""
      until:
        description: "종료일(YYYYMMDD), 비우면 어제"
        required: false
        default: ""
      force:
        description: "체크포인트 무시하고 다시 수집할지 (true/false)"
        required: false
        default: "false"
  schedule:
    # KST(+9) 기준 00:40 / 02:10 / 03:20 (UTC)
    - cron: "40 15 * * *"
    - cron: "10 17 * * *"
    - cron: "20 19 * * *"

permissions:
  contents: write

concurrency:
  group: kbo-csv-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 pandas

      - name: Resolve dates
        id: ds
        shell: bash
        run: |
          IN_SINCE="${{ github.event.inputs.since }}"
          IN_UNTIL="${{ github.event.inputs.until }}"
          FORCE="${{ github.event.inputs.force }}"
          echo "since=$IN_SINCE"  >> $GITHUB_OUTPUT
          echo "until=$IN_UNTIL"  >> $GITHUB_OUTPUT
          echo "force=$FORCE"     >> $GITHUB_OUTPUT

      - name: Run crawler (headless)
        run: |
          set -e
          python KBO_crawl.py \
            --since "${{ steps.ds.outputs.since }}" \
            --until "${{ steps.ds.outputs.until }}" \
            --out   "data/kbo_latest.csv" \
            --force "${{ steps.ds.outputs.force }}"

      - name: Commit CSV if changed
        id: commit
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/kbo_latest.csv
          if git diff --cached --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes to commit."
          else
            git commit -m "chore(data): auto-update kbo_latest.csv [skip ci]"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push
        if: steps.commit.outputs.changes == 'true'
        run: git push
