name: Update KBO CSV daily

on:
  workflow_dispatch:
    inputs:
      since:
        description: "수집 시작일(YYYYMMDD)"
        required: false
        default: "20250322"
      until:
        description: "수집 종료일(YYYYMMDD, 미지정 시 오늘)"
        required: false
        default: ""
  schedule:
    # KST(+9) 기준 분산 3회 (UTC로 기입)
    - cron: "40 14 * * *"   # 23:40 KST
    - cron: "10 16 * * *"   # 01:10 KST
    - cron: "20 18 * * *"   # 03:20 KST

permissions:
  contents: write   # CSV 커밋/푸시 위해 필요

# 동시 실행 제한 (대기 누적 방지)
concurrency:
  group: kbo-csv-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul   # 로그/시간대 고정
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install selenium beautifulsoup4 pandas numpy requests

      - name: Resolve inputs
        id: ds
        shell: bash
        run: |
          SINCE="${{ github.event.inputs.since }}"
          UNTIL="${{ github.event.inputs.until }}"
          if [ -z "$SINCE" ]; then SINCE="20250322"; fi
          echo "since=$SINCE"   >> $GITHUB_OUTPUT
          echo "until=$UNTIL"   >> $GITHUB_OUTPUT
          echo "Resolved -> since=$SINCE until=$UNTIL"

      - name: Run crawler (headless)
        run: |
          set -e
          SINCE="${{ steps.ds.outputs.since }}"
          UNTIL="${{ steps.ds.outputs.until }}"
          OUT="data/kbo_latest.csv"
          if [ -z "$UNTIL" ]; then
            python KBO_crawl.py --since "$SINCE" --out "$OUT"
          else
            python KBO_crawl.py --since "$SINCE" --until "$UNTIL" --out "$OUT"
          fi
          ls -lh "$OUT" || true

      - name: Commit CSV if changed
        id: commit
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/kbo_latest.csv
          if git diff --cached --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes to commit."
          else
            git commit -m "chore(data): auto-update kbo_latest.csv [skip ci]"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push
        if: steps.commit.outputs.changes == 'true'
        run: |
          git push

      - name: Upload artifact (CSV)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kbo-csv
          path: data/kbo_latest.csv
          if-no-files-found: ignore
