name: Update KBO CSV daily

on:
  workflow_dispatch: {}
  schedule:
    - cron: "40 16 * * *"   # 매일 01:40 KST
    - cron: "30 18 * * *"   # 매일 03:30 KST
    - cron: "10 21 * * *"   # 매일 06:10 KST
    
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium beautifulsoup4 pandas numpy requests

      - name: Run crawler (headless)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python KBO_crawl.py
          ls -lh kbo_games_ultra_precise_*.csv || true

      - name: Merge into data/kbo_latest.csv (dedupe)
        run: |
          python - << 'PY'
          import pandas as pd, glob, os
          latest_path = "data/kbo_latest.csv"
          os.makedirs("data", exist_ok=True)
          base = pd.read_csv(latest_path, encoding="utf-8-sig") if os.path.exists(latest_path) else pd.DataFrame()
          files = sorted(glob.glob("kbo_games_ultra_precise_*.csv"))
          if not files:
              print("No new crawl file; keep current.")
              raise SystemExit(0)
          new = pd.read_csv(files[-1], encoding="utf-8-sig")
          combined = pd.concat([base, new], ignore_index=True)
          combined = combined.drop_duplicates(subset=["date","away_team","home_team"], keep="last")
          combined["date"] = pd.to_datetime(combined["date"], errors="coerce")
          combined = combined.sort_values(["date","stadium","away_team","home_team"])
          combined["date"] = combined["date"].dt.strftime("%Y-%m-%d")
          combined.to_csv(latest_path, index=False, encoding="utf-8-sig")
          print("Wrote:", latest_path, "rows:", len(combined))
          PY

      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/kbo_latest.csv
          git commit -m "chore(data): auto-update kbo_latest.csv [skip ci]" || echo "No changes"
          git push
