name: Update KBO CSV

on:
  schedule:
    # 매일 23:30 KST (UTC 14:30)
    - cron: "30 17 * * *"
  workflow_dispatch:
    inputs:
      since:
        description: "YYYYMMDD (옵션, 하루/구간 시작)"
        required: false
      until:
        description: "YYYYMMDD (옵션, 하루/구간 끝)"
        required: false
      manual_dates:
        description: "콤마구분 날짜들 예: 20250901,20250903 (옵션)"
        required: false
      recent_re:
        description: "최근 강제 재크롤 경기 수(기본 3)"
        required: false

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      OUT: data/kbo_latest.csv
      RECHECK_DAYS: "7"
      RECENT_RECRAWL_GAMES: ${{ github.event.inputs.recent_re != '' && github.event.inputs.recent_re || '3' }}
      SINCE: ${{ github.event.inputs.since }}
      UNTIL: ${{ github.event.inputs.until }}
      MANUAL_DATES: ${{ github.event.inputs.manual_dates }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system libs (for Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libgbm1 libasound2 libxshmfence1 libgtk-3-0 libx11-xcb1 fonts-liberation

      - name: Install Google Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests==2.32.3 selenium==4.23.1 beautifulsoup4 pandas
          fi

      - name: Run crawler (append-mode aware + pending refresh)
        env:
          CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
        run: |
          set -ex
          python -u KBO_crawl.py

      - name: Commit CSV if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "data: refresh CSV (pending & recent recheck)"
          else
            echo "No file changes."
          fi

      - name: Push
        if: ${{ !cancelled() }}
        run: |
          AHEAD=$(git rev-list --left-right --count origin/$(git rev-parse --abbrev-ref HEAD)...HEAD | awk '{print $2}')
          if [[ "${AHEAD}" != "0" ]]; then
            git push
          else
            echo "Nothing to push."
          fi
